/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedReviewsIndexRouteImport } from './routes/_authed/reviews/index'
import { Route as AuthedEstablishmentsIndexRouteImport } from './routes/_authed/establishments/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as AuthedReviewsIdRouteImport } from './routes/_authed/reviews/$id'
import { Route as AuthedEstablishmentsNewRouteImport } from './routes/_authed/establishments/new'
import { Route as AuthedEstablishmentsIdRouteImport } from './routes/_authed/establishments/$id'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReviewsIndexRoute = AuthedReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEstablishmentsIndexRoute =
  AuthedEstablishmentsIndexRouteImport.update({
    id: '/establishments/',
    path: '/establishments/',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReviewsIdRoute = AuthedReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEstablishmentsNewRoute = AuthedEstablishmentsNewRouteImport.update({
  id: '/establishments/new',
  path: '/establishments/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEstablishmentsIdRoute = AuthedEstablishmentsIdRouteImport.update({
  id: '/establishments/$id',
  path: '/establishments/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/establishments/$id': typeof AuthedEstablishmentsIdRoute
  '/establishments/new': typeof AuthedEstablishmentsNewRoute
  '/reviews/$id': typeof AuthedReviewsIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/establishments/': typeof AuthedEstablishmentsIndexRoute
  '/reviews/': typeof AuthedReviewsIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/establishments/$id': typeof AuthedEstablishmentsIdRoute
  '/establishments/new': typeof AuthedEstablishmentsNewRoute
  '/reviews/$id': typeof AuthedReviewsIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/establishments': typeof AuthedEstablishmentsIndexRoute
  '/reviews': typeof AuthedReviewsIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/establishments/$id': typeof AuthedEstablishmentsIdRoute
  '/_authed/establishments/new': typeof AuthedEstablishmentsNewRoute
  '/_authed/reviews/$id': typeof AuthedReviewsIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/_authed/establishments/': typeof AuthedEstablishmentsIndexRoute
  '/_authed/reviews/': typeof AuthedReviewsIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/dashboard'
    | '/establishments/$id'
    | '/establishments/new'
    | '/reviews/$id'
    | '/api/webhooks/clerk'
    | '/establishments/'
    | '/reviews/'
    | '/api/oauth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/dashboard'
    | '/establishments/$id'
    | '/establishments/new'
    | '/reviews/$id'
    | '/api/webhooks/clerk'
    | '/establishments'
    | '/reviews'
    | '/api/oauth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/_authed/dashboard'
    | '/_authed/establishments/$id'
    | '/_authed/establishments/new'
    | '/_authed/reviews/$id'
    | '/api/webhooks/clerk'
    | '/_authed/establishments/'
    | '/_authed/reviews/'
    | '/api/oauth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reviews/': {
      id: '/_authed/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthedReviewsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/establishments/': {
      id: '/_authed/establishments/'
      path: '/establishments'
      fullPath: '/establishments/'
      preLoaderRoute: typeof AuthedEstablishmentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/reviews/$id': {
      id: '/_authed/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof AuthedReviewsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/establishments/new': {
      id: '/_authed/establishments/new'
      path: '/establishments/new'
      fullPath: '/establishments/new'
      preLoaderRoute: typeof AuthedEstablishmentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/establishments/$id': {
      id: '/_authed/establishments/$id'
      path: '/establishments/$id'
      fullPath: '/establishments/$id'
      preLoaderRoute: typeof AuthedEstablishmentsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedEstablishmentsIdRoute: typeof AuthedEstablishmentsIdRoute
  AuthedEstablishmentsNewRoute: typeof AuthedEstablishmentsNewRoute
  AuthedReviewsIdRoute: typeof AuthedReviewsIdRoute
  AuthedEstablishmentsIndexRoute: typeof AuthedEstablishmentsIndexRoute
  AuthedReviewsIndexRoute: typeof AuthedReviewsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedEstablishmentsIdRoute: AuthedEstablishmentsIdRoute,
  AuthedEstablishmentsNewRoute: AuthedEstablishmentsNewRoute,
  AuthedReviewsIdRoute: AuthedReviewsIdRoute,
  AuthedEstablishmentsIndexRoute: AuthedEstablishmentsIndexRoute,
  AuthedReviewsIndexRoute: AuthedReviewsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
